App\ExperienceDatabase\Experience:
  extensions:
    - PurpleSpider\BasicGalleryExtension\PhotoGalleryExtension
  gallery-title: Galerie
  gallery-cms-tab: Galerie
  content-cms-tab: Top Content

SilverStripe\Control\Session:
    cookie_domain: .domain.test

Level51\JWTUtils\JWTUtils:
  secret: 'jsdjhvcnuehbgzchfnzs#382nd718nd81'       # Secret for signature. This is mandatory and there is no default value
  lifetime_in_days: 7             # Term of validity
  renew_threshold_in_minutes: 60  # Keep JWT for at least 60 minutes
