SilverStripe\Security\Member:
  extensions:
    - App\Extensions\ExperienceMemberExtension

SilverStripe\MimeValidator\MimeUploadValidator:
  MimeTypes:
    svg:
      - 'image/svg+xml'
      - 'image/svg'

SilverStripe\Assets\File:
    allowed_extensions:
    - svg
